app/models/user.py
from app import db, login, ma
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    username = db.Column(db.String(50), index=True, unique=True)
    email = db.Column(db.String(255), index=True, unique=True, nullable=False)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return "<User '{}' with id '{}'>".format(self.username, self.id)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)


@login.user_loader
def load_user(id):
    return User.query.get(int(id))


class UserSchema(ma.Schema):
    class Meta:
        fields = ('id', 'username', 'email', '_links')
    _links = ma.Hyperlinks({
        'self': ma.URLFor('api.user_detail', id='<id>'),
        'collection': ma.URLFor('api.users')
    })


user_schema = UserSchema()
users_schema = UserSchema(many=True)

app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from flask_marshmallow import Marshmallow
from config import Config
from apispec import APISpec
from flask_apispec.extension import FlaskApiSpec

db = SQLAlchemy()
migrate = Migrate()
bootstrap = Bootstrap()
login = LoginManager()
login.login_view = 'auth.login'
login.login_message = 'Please log in to access this page.'
ma = Marshmallow()
docs = FlaskApiSpec()


def create_app(config_class=Config):
    app2 = Flask(__name__)
    app2.config.from_object(Config)

    db.init_app(app2)
    migrate.init_app(app2, db)
    bootstrap.init_app(app2)
    login.init_app(app2)
    ma.init_app(app2)

    app2.config.update({
        'APISPEC_SPEC': APISpec(
            title='BlaBla',
            version='v1',
            plugins=['apispec.ext.marshmallow'],
        ),
        'APISPEC_SWAGGER_URL': '/swagger/',
    })

    docs.init_app(app2)

    from app.api import bp as api_bp
    app2.register_blueprint(api_bp, url_prefix='/api')

    from app.api.users import users, user_detail
    docs.register(users, blueprint='api')
    docs.register(user_detail, blueprint='api')

    from app.main import bp as main_bp
    app2.register_blueprint(main_bp)

    from app.auth import bp as auth_bp
    app2.register_blueprint(auth_bp)

    from app.blog import bp as blog_bp
    app2.register_blueprint(blog_bp, url_prefix='/blog')

    return app2

app/api/__init__.py
from flask import Blueprint


bp = Blueprint('api', __name__)


from app.api import users

app/blog/__init__.py
from flask import Blueprint
from flask import redirect, url_for, request
from flask_login import current_user


bp = Blueprint('blog', __name__)


@bp.before_request
def retrict_bp():
    if not current_user.is_authenticated:
        return redirect(url_for('auth.login', next=request.path))


from app.blog import routes

app/blog/routes.py
from flask import render_template
from app.blog import bp


@bp.route('/', methods=['GET'])
@bp.route('/index', methods=['GET'])
def index():
    return render_template('blog/index.html', title='Blog')

app/main/__init__.py
from flask import Blueprint


bp = Blueprint('main', __name__)


from app.main import routes

app/main/routes.py
from flask import render_template
from app.main import bp


@bp.route('/', methods=['GET'])
@bp.route('/index', methods=['GET'])
def index():
    return render_template('index.html', title='Home')

app/templates/base.html
{% extends 'bootstrap/base.html' %}

{% block title %}
    {% if title %}{{ title }} - FlaskApp{% else %}FlaskApp{% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">FlaskApp</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.index') }}">Home</a></li>
                    <li><a href="{{ url_for('blog.index') }}">Blog</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                  {% if current_user.is_anonymous %}
                  <li><a href="{{ url_for('auth.login') }}">Login</a></li>
                  {% else %}
                  <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
                  {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}
        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/blog/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Welcome To Blog</h1>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}
    <h1>Welcome To FlaskApp</h1>
{% endblock %}